name: Max Wink
favicon: null
layout_spectrum: 0.4504578956402838
typography_spectrum: 0.8818059139885008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.07563999202102423
  lightness: 0.9924580773804337
  saturation: 0.8383951049763709
  rhythmicContrast: 0.5198317521717399
purpose: []
