name: Max Wink
favicon: null
layout_spectrum: 0.4504578956402838
typography_spectrum: 0.8818059139885008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#09090b'
    - '#688fd0'
    - '#653d35'
    - '#b4a495'
  brandStrength: 0.0625
  lightness: 0.9924580773804337
  saturation: 0.8383951049763709
  rhythmicContrast: 0.5198317521717399
purpose: []
